swagger: '2.0'
info:
  version: '1.0'
  title: 'Ehgzly''s Application'
  description: >-
    Ehgzly application is one of the most succeeded startups in egypt, developed
    with love by Fawzi E. Abdulfattah. 
host: "localhost:3000"
basePath: "/api"
paths:
  /signup:
    post:
      tags:
      - "users"
      summary: "Signup a new user"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Required Information to register a user"
        required: true
        schema:
          $ref: "#/definitions/signup_body"
      responses:
        '201':
          description: 201 (Created - User Created Successfully)
          schema:
            $ref: '#/definitions/signup_response'
        '409':
          description: 409 (CONFLICT - Phone number already registered)
          schema:
            $ref: '#/definitions/error_409'
        '400':
          description: 400 (Bad Request - input is incorrect or missing)
          schema:
            $ref: '#/definitions/error_400'
definitions:
 signup_body:
    type: "object"
    example: 
      phone_number: 01090243795
      first_name: fawzi
      last_name: essam
      country: egypt
      city: portsaid
      firebase_token: '93484893983498'
 signup_response:
    type: "object"
    example: 
      status: true
      message: success
      data:
        status: true
        message: success
        data:
          user_id: 1
          phone_number: 01090243795
          first_name: fawzi
          last_name: essam
          country: egypt
          city: portsaid
          wallet: 0
          firebase_token: '93484893983498'
          refresh_token: 0a2eb08bf0c7caf5d27412fbe75ab4c4
          token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZV9udW1iZXIiOiIwMTA5MDI0Mzc5NSIsInVzZXJfaWQiOjEsImlhdCI6MTU5NDMzMDk0MSwiZXhwIjoxNTk0Mzc0MTQxfQ.i1g7IC0s1XpLDoiOCGu64lhinD3deQmmSERk5StjHjI
        
 error_409:
    type: "object"
    description: "CONFLICT"
    example:
      status: true
      message: "Error explaniation will be shown here"
      data: []
  
 error_401:
    type: "string"
    description: "Unauthorized"
    example:
      status: true
      message: "Error explaniation will be shown here"
      data: []
 error_400:
    type: "string"
    description: "Bad Request"
    example:
      status: true
      message: "Error explaniation will be shown here"
      data: []
